name: Rust run Workflow

on:
  push:
    branches: [main]

jobs:
  build:
    name: Run day
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Build
        run: make build

      - name: Run
        run: make run
